/**
 * Executive-brief generation surface: generation lifecycle types, version
 * listing, status polling, and PDF/PPTX export. The brief lives on a
 * workstream card and is async-generated, so callers typically `generateBrief`
 * → poll `getBriefStatus` → `getBrief` for content.
 *
 * @module lib/workstream/brief
 */

import { API_BASE_URL } from "../config";
import { apiRequest } from "./shared";

// ----------------------------------------------------------------------------
// Types
// ----------------------------------------------------------------------------

/**
 * Executive brief generation status values.
 * Represents the lifecycle of an AI-generated brief:
 * - pending: Brief generation has been requested but not started
 * - generating: Brief is actively being generated by the AI
 * - completed: Brief has been successfully generated
 * - failed: Brief generation encountered an error
 */
export type BriefGenerationStatus =
  | "pending"
  | "generating"
  | "completed"
  | "failed";

/**
 * Executive brief for a workstream card.
 * Contains AI-generated content summarizing the card for leadership review.
 */
export interface ExecutiveBrief {
  /** Unique identifier for the brief */
  id: string;
  /** UUID of the workstream card this brief belongs to */
  workstream_card_id: string;
  /** UUID of the underlying intelligence card */
  card_id: string;
  /** UUID of the user who created/requested the brief */
  created_by: string;
  /** Current generation status */
  status: BriefGenerationStatus;
  /** Version number (1, 2, 3, etc.) */
  version: number;
  /** Metadata about sources discovered since previous version */
  sources_since_previous: {
    count: number;
    since_version: number;
    since_date: string;
  } | null;
  /** Structured brief content (JSON format) */
  content: Record<string, unknown> | null;
  /** Markdown-formatted brief content for display */
  content_markdown: string | null;
  /** Short summary of the brief (1-2 sentences) */
  summary: string | null;
  /** Timestamp when brief generation completed (ISO format) */
  generated_at: string | null;
  /** Time taken to generate the brief in milliseconds */
  generation_time_ms: number | null;
  /** AI model used for generation */
  model_used: string | null;
  /** Error message if generation failed */
  error_message: string | null;
  /** Creation timestamp (ISO format) */
  created_at: string;
  /** Last update timestamp (ISO format) */
  updated_at: string;
}

/**
 * Lightweight status response for polling brief generation progress.
 * Used to check if generation is complete without fetching full content.
 */
export interface BriefStatus {
  /** Brief identifier */
  id: string;
  /** Current generation status */
  status: BriefGenerationStatus;
  /** Version number being generated */
  version: number;
  /** Short summary (available once completed) */
  summary: string | null;
  /** Error message (available if failed) */
  error_message: string | null;
  /** Timestamp when generation completed */
  generated_at: string | null;
  /** Progress message during generation */
  progress_message: string | null;
}

/**
 * Response from initiating brief generation.
 */
export interface GenerateBriefResponse {
  /** Unique identifier for the brief */
  id: string;
  /** Initial status (typically 'pending' or 'generating') */
  status: string;
  /** Version number being generated */
  version: number;
  /** Status message */
  message: string;
}

/**
 * Compact version item for version history display.
 */
export interface BriefVersionListItem {
  /** Unique identifier for this version */
  id: string;
  /** Version number (1, 2, 3, etc.) */
  version: number;
  /** Generation status */
  status: BriefGenerationStatus;
  /** Short summary for preview */
  summary: string | null;
  /** Metadata about new sources since previous version */
  sources_since_previous: {
    count: number;
    since_version: number;
    since_date: string;
  } | null;
  /** Timestamp when generation completed */
  generated_at: string | null;
  /** Timestamp when record was created */
  created_at: string;
  /** AI model used */
  model_used: string | null;
}

/**
 * Response containing all versions of a brief.
 */
export interface BriefVersionsResponse {
  /** UUID of the workstream card */
  workstream_card_id: string;
  /** UUID of the underlying card */
  card_id: string;
  /** Total number of versions */
  total_versions: number;
  /** List of versions, newest first */
  versions: BriefVersionListItem[];
}

// ----------------------------------------------------------------------------
// Generation + retrieval
// ----------------------------------------------------------------------------

/**
 * Initiates executive brief generation for a workstream card.
 * This is an async operation - the brief will be generated in the background.
 * Use getBriefStatus() to poll for completion, then getBrief() to fetch the result.
 *
 * @param token - Bearer authentication token
 * @param workstreamId - UUID of the workstream
 * @param cardId - UUID of the workstream card (not the underlying card)
 * @returns Initial response with brief ID and status
 *
 * @example
 * ```typescript
 * const response = await generateBrief(token, wsId, cardId);
 * console.log(`Brief ${response.id} generation started with status: ${response.status}`);
 * // Poll getBriefStatus() until status is 'completed' or 'failed'
 * ```
 */
export async function generateBrief(
  token: string,
  workstreamId: string,
  cardId: string,
): Promise<GenerateBriefResponse> {
  return apiRequest<GenerateBriefResponse>(
    `/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief`,
    token,
    {
      method: "POST",
    },
  );
}

/**
 * Fetches the full executive brief for a workstream card.
 * Call this after brief generation is complete to get the full content.
 *
 * @param token - Bearer authentication token
 * @param workstreamId - UUID of the workstream
 * @param cardId - UUID of the workstream card
 * @param version - Optional specific version to fetch (defaults to latest)
 * @returns The complete executive brief with all content
 *
 * @example
 * ```typescript
 * const brief = await getBrief(token, wsId, cardId);
 * if (brief.status === 'completed') {
 *   console.log(brief.content_markdown);
 * }
 * // Fetch a specific version
 * const v1 = await getBrief(token, wsId, cardId, 1);
 * ```
 */
export async function getBrief(
  token: string,
  workstreamId: string,
  cardId: string,
  version?: number,
): Promise<ExecutiveBrief> {
  const url = version
    ? `/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief?version=${version}`
    : `/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief`;
  return apiRequest<ExecutiveBrief>(url, token);
}

/**
 * Fetches all versions of briefs for a workstream card.
 * Returns versions ordered by version number descending (newest first).
 *
 * @param token - Bearer authentication token
 * @param workstreamId - UUID of the workstream
 * @param cardId - UUID of the workstream card
 * @returns List of all brief versions with metadata
 *
 * @example
 * ```typescript
 * const { versions, total_versions } = await getBriefVersions(token, wsId, cardId);
 * versions.forEach(v => console.log(`v${v.version}: ${v.summary}`));
 * ```
 */
export async function getBriefVersions(
  token: string,
  workstreamId: string,
  cardId: string,
): Promise<BriefVersionsResponse> {
  return apiRequest<BriefVersionsResponse>(
    `/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief/versions`,
    token,
  );
}

/**
 * Checks the current status of brief generation.
 * Use this for polling during async brief generation to minimize data transfer.
 * Once status is 'completed', call getBrief() to fetch the full content.
 *
 * @param token - Bearer authentication token
 * @param workstreamId - UUID of the workstream
 * @param cardId - UUID of the workstream card
 * @returns Lightweight status object with generation progress
 *
 * @example
 * ```typescript
 * const status = await getBriefStatus(token, wsId, cardId);
 * if (status.status === 'completed') {
 *   const brief = await getBrief(token, wsId, cardId);
 * } else if (status.status === 'failed') {
 *   console.error(status.error_message);
 * }
 * ```
 */
export async function getBriefStatus(
  token: string,
  workstreamId: string,
  cardId: string,
): Promise<BriefStatus> {
  return apiRequest<BriefStatus>(
    `/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief/status`,
    token,
  );
}

// ----------------------------------------------------------------------------
// Export
// ----------------------------------------------------------------------------

/**
 * Exports an executive brief in the specified format.
 * Downloads the brief content (not the original card) as PDF or PowerPoint.
 *
 * @param token - Bearer authentication token
 * @param workstreamId - UUID of the workstream
 * @param cardId - UUID of the workstream card
 * @param format - Export format ('pdf' or 'pptx')
 * @param version - Optional version number to export (defaults to latest)
 * @returns true if export was successful
 *
 * @example
 * ```typescript
 * const success = await exportBrief(token, wsId, cardId, 'pdf');
 * if (success) {
 *   console.log('Brief downloaded as PDF');
 * }
 * ```
 */
export async function exportBrief(
  token: string,
  workstreamId: string,
  cardId: string,
  format: "pdf" | "pptx",
  version?: number,
): Promise<boolean> {
  const url = version
    ? `${API_BASE_URL}/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief/export/${format}?version=${version}`
    : `${API_BASE_URL}/api/v1/me/workstreams/${workstreamId}/cards/${cardId}/brief/export/${format}`;

  try {
    const response = await fetch(url, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      const contentType = response.headers.get("content-type");
      if (contentType?.includes("application/json")) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(
          errorData.detail ||
            errorData.message ||
            `Export failed: ${response.status}`,
        );
      }
      throw new Error(`Export failed: ${response.status}`);
    }

    // Get the blob and trigger download
    const blob = await response.blob();

    // Extract filename from Content-Disposition header or use default
    const contentDisposition = response.headers.get("content-disposition");
    let filename = `brief-export.${format}`;

    if (contentDisposition) {
      const filenameMatch = contentDisposition.match(
        /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/,
      );
      if (filenameMatch && filenameMatch[1]) {
        filename = filenameMatch[1].replace(/['"]/g, "");
      }
    }

    // Create download link and trigger click
    const downloadUrl = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = downloadUrl;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(downloadUrl);

    return true;
  } catch (error) {
    console.error("Brief export failed:", error);
    throw error;
  }
}
