-- Migration: research_tasks_shared_card_read
-- Created at: 20260603000001
-- Description:
--   Make deep-research "Strategic Intelligence Reports" readable across users
--   when they are attached to a card.
--
--   Background / root cause (diagnosed 2026-06-03):
--     Deep-research reports are stored on research_tasks.result_summary
--     (report_preview) and surfaced as CARD-LEVEL shared intelligence:
--       - The card "has deep research" badge is computed server-side with the
--         service-role key (app/card_artifacts.py), which bypasses RLS and
--         therefore sees every user's reports.
--       - The Deep Research tab, however, queries research_tasks DIRECTLY from
--         the browser session (useCardData.ts) under RLS.
--     The only authenticated read policy was owner-scoped
--     (research_tasks_own: auth.uid() = user_id), so a report generated by
--     user A was invisible to user B on the same card. The badge advertised a
--     report the tab could not display ("No Strategic Intelligence Reports
--     Yet" on a card whose badge says it has one).
--
--   Fix:
--     Any authenticated user may READ research_tasks rows that are attached to
--     a card (card_id IS NOT NULL). This matches the public-read card library
--     (cards_public_read … USING (true)) and the service-role badge semantics.
--     Writes stay strictly owner-scoped, and workstream-only analyses
--     (card_id IS NULL) remain private to their owner.
--
--   Lint notes: a single combined SELECT policy avoids the
--   multiple_permissive_policies warning, and (select auth.uid()) avoids the
--   auth_rls_initplan warning — consistent with migrations 1766739200 /
--   1766739201. The service role keeps full access via BYPASSRLS (no policy
--   needed).

BEGIN;

-- Replace the single FOR ALL owner policy with command-specific policies so
-- the SELECT condition can be broadened without loosening writes.
DROP POLICY IF EXISTS research_tasks_own ON public.research_tasks;

-- READ: your own rows (any task type) OR any card-attached research task.
CREATE POLICY research_tasks_select ON public.research_tasks
    FOR SELECT
    TO authenticated
    USING (
        (select auth.uid()) = user_id
        OR card_id IS NOT NULL
    );

-- WRITE: strictly owner-scoped (defense-in-depth; production writes go through
-- the service-role backend, which bypasses RLS).
CREATE POLICY research_tasks_insert ON public.research_tasks
    FOR INSERT
    TO authenticated
    WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY research_tasks_update ON public.research_tasks
    FOR UPDATE
    TO authenticated
    USING ((select auth.uid()) = user_id)
    WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY research_tasks_delete ON public.research_tasks
    FOR DELETE
    TO authenticated
    USING ((select auth.uid()) = user_id);

COMMIT;
